### ISSUE TITLE
There's no latest tag

### ISSUE THREAD

**Issue by drpaneas** [openSUSE/helm-mirror#10]
Currently:

```bash
curl --silent https://github.com/openSUSE/helm-mirror/releases/latest
<html><body>You are being <a href="https://github.com/openSUSE/helm-mirror/releases">redirected</a>.</body></html>
```

It should be something like that (example is from minikube):

```bash
curl --silent https://github.com/kubernetes/minikube/releases/latest
<html><body>You are being <a href="https://github.com/kubernetes/minikube/releases/tag/v0.30.0">redirected</a>.</body></html>
```

I think this is because it is flagged as pre-release atm, but I am not sure how this works.

**Comment by chentex** [comment]
@drpaneas I think it is related to only having an alpha review, I want to tackle a couple of issues ( #8 and #9 ) to have a latest.

**Comment by chentex** [comment]
Resolved with new release
