### ISSUE TITLE
Do not use the API for fetching the tgz

### ISSUE THREAD

**Issue by drpaneas** [openSUSE/helm-mirror#9]
The `install-binary.sh` fails.

```bash
+ local url=https://api.github.com/repos/openSUSE/helm-mirror/releases/latest
+ type curl
++ curl -s https://api.github.com/repos/openSUSE/helm-mirror/releases/latest
++ grep linux
++ awk '/\"browser_download_url\":/{gsub( /[,\"]/,"", $2); print $2}'
+ DOWNLOAD_URL=
+ downloadFile
+ PLUGIN_TMP_FILE=/tmp/helm-mirror.tgz
+ echo 'Downloading '
Downloading 
+ type curl
+ curl -L '' -o /tmp/helm-mirror.tgz
curl: (3) <url> malformed
+ fail_trap
+ result=3
+ '[' 3 '!=' 0 ']'
+ echo 'Failed to install helm-mirror'
```

This fails because you send a request via the `api.github.com`. Depending on the organization, there might be that the free limit is already exhausted. In my case:

```
"API rate limit exceeded for 195.135.221.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
```

Read: https://developer.github.com/v3/#rate-limiting

**Comment by anannaya** [comment]
Hi,
I am getting below error,
`
+ PROJECT_NAME=helm-mirror
+ PROJECT_GH=openSUSE/helm-mirror
++ helm home --debug=false
+ : /root/.helm/plugins/helm-mirror
+ type cygpath
+ [[ '' == \1 ]]
+ trap fail_trap EXIT
+ set -e
+ initArch
++ uname -m
+ ARCH=x86_64
+ case $ARCH in
+ ARCH=amd64
+ initOS
++ tr '[:upper:]' '[:lower:]'
+++ uname
++ echo Linux
+ OS=linux
+ case "$OS" in
+ verifySupported
+ local supported=linux-amd64
+ echo linux-amd64
+ grep -q linux-amd64
+ type curl
+ getDownloadURL
++ git -C /root/.helm/plugins/helm-mirror describe --tags --exact-match
+ local version=
+ '[' -n '' ']'
+ local url=https://github.com/repos/openSUSE/helm-mirror/releases/latest
+ type curl
++ curl -s https://github.com/repos/openSUSE/helm-mirror/releases/latest
++ grep -o -E 'v.+\"'
++ awk '{split($0,a,/"/); print a[1]}'
+ version=
+ DOWNLOAD_URL=https://codeload.github.com/openSUSE/helm-mirror/tar.gz/
+ echo 'using download url https://codeload.github.com/openSUSE/helm-mirror/tar.gz/'
using download url https://codeload.github.com/openSUSE/helm-mirror/tar.gz/
+ downloadFile
+ PLUGIN_TMP_FILE=/tmp/helm-mirror.tgz
+ echo 'Downloading https://codeload.github.com/openSUSE/helm-mirror/tar.gz/'
Downloading https://codeload.github.com/openSUSE/helm-mirror/tar.gz/
+ type curl
+ curl -L https://codeload.github.com/openSUSE/helm-mirror/tar.gz/ -o /tmp/helm-mirror.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     22      0 --:--:-- --:--:-- --:--:--    22
+ installFile
+ HELM_TMP=/tmp/helm-mirror
+ mkdir -p /tmp/helm-mirror
+ tar xf /tmp/helm-mirror.tgz -C /tmp/helm-mirror --strip-components=1
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
+ fail_trap
+ result=2
+ '[' 2 '!=' 0 ']'
+ echo 'Failed to install helm-mirror'
Failed to install helm-mirror
+ echo 'For support, go to https://github.com/openSUSE/helm-mirror.'
For support, go to https://github.com/openSUSE/helm-mirror.
+ exit 2

`
